### ISSUE TITLE
update app image in README

### ISSUE THREAD

**Issue by nuexq** [Abdo-Nsila/The-Prayer-Project#5]
I have an image for it, I already try to do it my self but vercel doesn't let me murge the pull request with this message "all checks have failed "

![image](https://github.com/Abdo-Nsila/The-Prayer-Project/assets/145666753/bb5a0b26-f30a-4a7b-b568-610bd5ce1f5b)

**Comment by Abdo-Nsila** [comment]
![vercel auth](https://github.com/Abdo-Nsila/The-Prayer-Project/assets/126418751/c73971a1-8762-4c23-9023-e4b58eab658f)



Could you please reopen the pull request so that I can review and authorize it? So, I can't create a team on Vercel with my free plan to add you to this project, but if I can authorize your pull request, that should suffice.

**Comment by nuexq** [comment]
ok i well reopen it

**Comment by nuexq** [comment]
i creat a new pull request cuz the prev pull request doesn't want to reopen

**Comment by Abdo-Nsila** [comment]
The pull request has been successfully merged. At first, I noticed that the image did not change; It appears that the new photo was deleted and the old photo was added again. So, I had to revert the pull request, change the image, and then merge the branch again. Everything now works fine. Thank you very much!
